/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as CompooperRouteRouteImport } from './routes/compooper/route'
import { Route as DownloadRouteImport } from './routes/download'
import { Route as HelpRouteImport } from './routes/help'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MapRouteImport } from './routes/map'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as CompooperIndexRouteImport } from './routes/compooper/index'
import { Route as CompooperDownloadRouteImport } from './routes/compooper/download'
import { Route as CompooperMapRouteImport } from './routes/compooper/map'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const CompooperRouteRoute = CompooperRouteRouteImport.update({
  id: '/compooper',
  path: '/compooper',
  getParentRoute: () => rootRouteImport,
} as any)
const DownloadRoute = DownloadRouteImport.update({
  id: '/download',
  path: '/download',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpRoute = HelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MapRoute = MapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const CompooperIndexRoute = CompooperIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CompooperRouteRoute,
} as any)
const CompooperDownloadRoute = CompooperDownloadRouteImport.update({
  id: '/download',
  path: '/download',
  getParentRoute: () => CompooperRouteRoute,
} as any)
const CompooperMapRoute = CompooperMapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => CompooperRouteRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/compooper': typeof CompooperRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/download': typeof DownloadRoute
  '/help': typeof HelpRoute
  '/login': typeof LoginRoute
  '/map': typeof MapRoute
  '/privacy': typeof PrivacyRoute
  '/compooper/download': typeof CompooperDownloadRoute
  '/compooper/map': typeof CompooperMapRoute
  '/compooper/': typeof CompooperIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/download': typeof DownloadRoute
  '/help': typeof HelpRoute
  '/login': typeof LoginRoute
  '/map': typeof MapRoute
  '/privacy': typeof PrivacyRoute
  '/compooper/download': typeof CompooperDownloadRoute
  '/compooper/map': typeof CompooperMapRoute
  '/compooper': typeof CompooperIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/compooper': typeof CompooperRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/download': typeof DownloadRoute
  '/help': typeof HelpRoute
  '/login': typeof LoginRoute
  '/map': typeof MapRoute
  '/privacy': typeof PrivacyRoute
  '/compooper/download': typeof CompooperDownloadRoute
  '/compooper/map': typeof CompooperMapRoute
  '/compooper/': typeof CompooperIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/compooper'
    | '/about'
    | '/download'
    | '/help'
    | '/login'
    | '/map'
    | '/privacy'
    | '/compooper/download'
    | '/compooper/map'
    | '/compooper/'
    | '/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/download'
    | '/help'
    | '/login'
    | '/map'
    | '/privacy'
    | '/compooper/download'
    | '/compooper/map'
    | '/compooper'
    | '/api/auth/$'
  id:
    | '__root__'
    | '/'
    | '/compooper'
    | '/about'
    | '/download'
    | '/help'
    | '/login'
    | '/map'
    | '/privacy'
    | '/compooper/download'
    | '/compooper/map'
    | '/compooper/'
    | '/api/auth/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CompooperRouteRoute: typeof CompooperRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  DownloadRoute: typeof DownloadRoute
  HelpRoute: typeof HelpRoute
  LoginRoute: typeof LoginRoute
  MapRoute: typeof MapRoute
  PrivacyRoute: typeof PrivacyRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compooper': {
      id: '/compooper'
      path: '/compooper'
      fullPath: '/compooper'
      preLoaderRoute: typeof CompooperRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/download': {
      id: '/download'
      path: '/download'
      fullPath: '/download'
      preLoaderRoute: typeof DownloadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help': {
      id: '/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof HelpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/map': {
      id: '/map'
      path: '/map'
      fullPath: '/map'
      preLoaderRoute: typeof MapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compooper/': {
      id: '/compooper/'
      path: '/'
      fullPath: '/compooper/'
      preLoaderRoute: typeof CompooperIndexRouteImport
      parentRoute: typeof CompooperRouteRoute
    }
    '/compooper/download': {
      id: '/compooper/download'
      path: '/download'
      fullPath: '/compooper/download'
      preLoaderRoute: typeof CompooperDownloadRouteImport
      parentRoute: typeof CompooperRouteRoute
    }
    '/compooper/map': {
      id: '/compooper/map'
      path: '/map'
      fullPath: '/compooper/map'
      preLoaderRoute: typeof CompooperMapRouteImport
      parentRoute: typeof CompooperRouteRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface CompooperRouteRouteChildren {
  CompooperDownloadRoute: typeof CompooperDownloadRoute
  CompooperMapRoute: typeof CompooperMapRoute
  CompooperIndexRoute: typeof CompooperIndexRoute
}

const CompooperRouteRouteChildren: CompooperRouteRouteChildren = {
  CompooperDownloadRoute: CompooperDownloadRoute,
  CompooperMapRoute: CompooperMapRoute,
  CompooperIndexRoute: CompooperIndexRoute,
}

const CompooperRouteRouteWithChildren = CompooperRouteRoute._addFileChildren(
  CompooperRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CompooperRouteRoute: CompooperRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  DownloadRoute: DownloadRoute,
  HelpRoute: HelpRoute,
  LoginRoute: LoginRoute,
  MapRoute: MapRoute,
  PrivacyRoute: PrivacyRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
